name: mygame
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flame: ^1.18.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/background/far.png
    # - assets/images/background/mid.png
    # - assets/images/background/near.png
    - assets/images/player_ship.png
    - assets/images/collectible.png
    - assets/images/bullet.png

